name: .NET Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Change to your desired .NET version (6.x, 7.x)

    - name: Restore dependencies
      run: dotnet restore ./KeyRemap.sln

    - name: Build
      run: dotnet build ./KeyRemap.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./KeyRemap.Tests/KeyRemap.Tests.csproj --no-restore --verbosity normal
